$schema = "node_modules/wrangler/config-schema.json"
main = ".open-next/worker.js"
name = "redd-web"
compatibility_date = "2024-12-30"

[[compatibility_flags]]
flag = "nodejs_compat"

[[compatibility_flags]]
flag = "global_fetch_strictly_public"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "redd-web"

[build]
command = "npm run build-open"
cwd = "."
watch_dir = "src"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NODE_ENV = "production"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "your-clerk-publishable-key"
CLERK_SECRET_KEY = "your-clerk-secret-key"

# Environment-specific configurations
[env.preview]
name = "redd-web-preview"
route = "redd-web-preview.pages.dev/*"
vars = { NODE_ENV = "preview", NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "your-clerk-publishable-key-preview", CLERK_SECRET_KEY = "your-clerk-secret-key-preview" }

[env.production]
name = "redd-web-production"
route = "redd-web-production.pages.dev/*"
vars = { NODE_ENV = "production" }

# D1 Database (for future use)
# [[d1_databases]]
# binding = "DB"
# database_name = "redd-db"
# database_id = "your-database-id"

# R2 Storage (for future use)
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "redd-bucket"

# KV Storage (for future use)
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-id"
# preview_id = "your-preview-kv-id"

# Queue (for future use)
# [[queues.producers]]
# binding = "OCR_QUEUE"
# queue = "ocr-processing"

# [[queues.consumers]]
# queue = "ocr-processing"
# max_batch_size = 10
# max_retries = 3
