name = "redd-web"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.js"

[build]
command = "npm run build-open"
cwd = "."
watch_dir = "src"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NODE_ENV = "production"
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "your-clerk-publishable-key"
CLERK_SECRET_KEY = "your-clerk-secret-key"

# Environment-specific configurations
# Note: Cloudflare Pages will override these routes with actual deployment URLs
[env.preview]
name = "redd-web-preview"
# route will be set by Cloudflare Pages based on branch name
vars = { NODE_ENV = "preview", NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY = "your-clerk-publishable-key-preview", CLERK_SECRET_KEY = "your-clerk-secret-key-preview" }

[env.production]
name = "redd-web-production"
# route will be set by Cloudflare Pages for main branch
vars = { NODE_ENV = "production" }

# D1 Database (for future use)
# [[d1_databases]]
# binding = "DB"
# database_name = "redd-db"
# database_id = "your-database-id"

# R2 Storage (for future use)
# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "redd-bucket"

# KV Storage (for future use)
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-id"
# preview_id = "your-preview-kv-id"

# Queue (for future use)
# [[queues.producers]]
# binding = "OCR_QUEUE"
# queue = "ocr-processing"

# [[queues.consumers]]
# queue = "ocr-processing"
# max_batch_size = 10
# max_retries = 3
