name: Deploy to Cloudflare Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'apps/web/package-lock.json'

      - name: Install dependencies
        run: |
          cd apps/web
          echo "Installing dependencies..."
          npm install --no-audit --no-fund --verbose
          echo "Dependencies installed successfully"

      - name: Verify installation
        run: |
          cd apps/web
          echo "Verifying Node.js version: $(node --version)"
          echo "Verifying npm version: $(npm --version)"
          npm list --depth=0

      - name: Build for Cloudflare
        run: |
          cd apps/web
          echo "Building for Cloudflare..."
          npm run build-open
          echo "Build completed successfully"

      - name: Deploy to Cloudflare Pages
        run: |
          cd apps/web
          echo "Starting Cloudflare Pages deployment..."
          echo "Account ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
          echo "Deploying from directory: $(pwd)/.opennext/dist"
          ls -la .opennext/dist/
          npx wrangler pages deploy .opennext/dist --compatibility-date=2025-04-01 --compatibility-flags=nodejs_compat
          echo "Deployment completed successfully"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
